title: "Tips & Editors for YML"
#description: "Make your PlexMetaManager life easier"

baseurl: /yml-tips
url: https://l33tlamer.github.io

permalink: date

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

exclude:  
- .gitignore
- _config.yml
- CNAME
