title: "Tips & Editors for YML"
description: "Make your PlexMetaManager life easier"

#url: # (optional) https://example.com, defaults to http://localhost:4000 in development

permalink: date

remote_theme: pages-themes/modernist@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
# theme: minima 
plugins:
- jekyll-remote-theme

exclude:  
- .gitignore
- _config.yml
